export const RealTimeFileTransferStatusTableData = [
  {
    sessionId: 12839712893712,
    sessionType: "Standard",
    file: "img_00.png",
    fileType: "Image",
    status: "Successful",
    size: "25 Kb",
  },
  {
    sessionId: 12391238384991,
    sessionType: "Secure",
    file: "audi.mp3",
    fileType: "Audio",
    status: "Failed",
    size: "1 Mb",
  },
  {
    sessionId: 12391237684991,
    sessionType: "Wallet",
    file: "files.zip",
    fileType: "ZIP",
    status: "Successful",
    size: "14 Mb",
  },
  {
    sessionId: 18371928371239,
    sessionType: "Standard",
    file: "video_01.mp4",
    fileType: "Video",
    status: "In Progress",
    size: "45 Mb",
  },
  {
    sessionId: 19827398127382,
    sessionType: "Secure",
    file: "report.pdf",
    fileType: "Document",
    status: "Successful",
    size: "500 Kb",
  },
  {
    sessionId: 18726391827362,
    sessionType: "Wallet",
    file: "presentation.pptx",
    fileType: "Document",
    status: "Failed",
    size: "3 Mb",
  },
  {
    sessionId: 19283749837492,
    sessionType: "Standard",
    file: "song.wav",
    fileType: "Audio",
    status: "Successful",
    size: "6 Mb",
  },
  {
    sessionId: 12984759837495,
    sessionType: "Secure",
    file: "archive.tar.gz",
    fileType: "Compressed",
    status: "Successful",
    size: "80 Mb",
  },
  {
    sessionId: 18726398127377,
    sessionType: "Wallet",
    file: "clip.mov",
    fileType: "Video",
    status: "Failed",
    size: "60 Mb",
  },
  {
    sessionId: 19283749837495,
    sessionType: "Standard",
    file: "design.ai",
    fileType: "Vector",
    status: "Successful",
    size: "2 Mb",
  },
  {
    sessionId: 18726398127383,
    sessionType: "Secure",
    file: "game.iso",
    fileType: "Disk Image",
    status: "In Progress",
    size: "700 Mb",
  },
  {
    sessionId: 19283749837488,
    sessionType: "Wallet",
    file: "notes.txt",
    fileType: "Text",
    status: "Successful",
    size: "2 Kb",
  },
  {
    sessionId: 13847892384759,
    sessionType: "Standard",
    file: "graphic.psd",
    fileType: "Image",
    status: "Failed",
    size: "25 Mb",
  },
  {
    sessionId: 13847892384750,
    sessionType: "Secure",
    file: "backup.bak",
    fileType: "Backup",
    status: "Successful",
    size: "100 Mb",
  },
  {
    sessionId: 13847892384753,
    sessionType: "Wallet",
    file: "plugin.jar",
    fileType: "Java Archive",
    status: "Successful",
    size: "15 Mb",
  },
  {
    sessionId: 14823987234922,
    sessionType: "Standard",
    file: "logo.svg",
    fileType: "Vector",
    status: "Successful",
    size: "150 Kb",
  },
  {
    sessionId: 14823987234924,
    sessionType: "Secure",
    file: "photo.jpeg",
    fileType: "Image",
    status: "Failed",
    size: "5 Mb",
  },
  {
    sessionId: 14823987234928,
    sessionType: "Wallet",
    file: "spreadsheet.xls",
    fileType: "Document",
    status: "Successful",
    size: "1 Mb",
  },
  {
    sessionId: 15823987234929,
    sessionType: "Standard",
    file: "ebook.epub",
    fileType: "Ebook",
    status: "In Progress",
    size: "10 Mb",
  },
  {
    sessionId: 15823987234930,
    sessionType: "Secure",
    file: "code.js",
    fileType: "Code",
    status: "Successful",
    size: "25 Kb",
  },
  {
    sessionId: 15823987234933,
    sessionType: "Wallet",
    file: "sketch.dxf",
    fileType: "Vector",
    status: "Successful",
    size: "12 Mb",
  },
  {
    sessionId: 16823987234934,
    sessionType: "Standard",
    file: "presentation.key",
    fileType: "Document",
    status: "Failed",
    size: "4 Mb",
  },
  {
    sessionId: 16823987234935,
    sessionType: "Secure",
    file: "app.apk",
    fileType: "App",
    status: "Successful",
    size: "50 Mb",
  },
  {
    sessionId: 16823987234936,
    sessionType: "Wallet",
    file: "snapshot.heic",
    fileType: "Image",
    status: "Successful",
    size: "8 Mb",
  },
  {
    sessionId: 17823987234937,
    sessionType: "Standard",
    file: "database.sql",
    fileType: "Database",
    status: "Failed",
    size: "1 Gb",
  },
  {
    sessionId: 17823987234938,
    sessionType: "Secure",
    file: "book.pdf",
    fileType: "Document",
    status: "Successful",
    size: "3 Mb",
  },
];
